# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

write_bfile <- function(pBigMat, bed_file, threads = 0L, verbose = TRUE) {
    invisible(.Call('_simer_write_bfile', PACKAGE = 'simer', pBigMat, bed_file, threads, verbose))
}

read_bfile <- function(bed_file, pBigMat, maxLine, threads = 0L, verbose = TRUE) {
    invisible(.Call('_simer_read_bfile', PACKAGE = 'simer', bed_file, pBigMat, maxLine, threads, verbose))
}

emma_kinship <- function(pBigMat, threads = 0L, verbose = TRUE) {
    .Call('_simer_emma_kinship', PACKAGE = 'simer', pBigMat, threads, verbose)
}

GenoFilter <- function(pBigMat, keepInds = NULL, filterGeno = NULL, filterHWE = NULL, filterMind = NULL, filterMAF = NULL, threads = 0L, verbose = TRUE) {
    .Call('_simer_GenoFilter', PACKAGE = 'simer', pBigMat, keepInds, filterGeno, filterHWE, filterMind, filterMAF, threads, verbose)
}

Mat2BigMat <- function(pBigMat, mat, colIdx = NULL, op = 1L, threads = 0L) {
    invisible(.Call('_simer_Mat2BigMat', PACKAGE = 'simer', pBigMat, mat, colIdx, op, threads))
}

BigMat2BigMat <- function(pBigMat, pBigmat, colIdx = NULL, op = 1L, threads = 0L) {
    invisible(.Call('_simer_BigMat2BigMat', PACKAGE = 'simer', pBigMat, pBigmat, colIdx, op, threads))
}

GenoMixer <- function(pBigMat, pBigmat, sirIdx, damIdx, nBlock = 100L, op = 1L, threads = 0L) {
    invisible(.Call('_simer_GenoMixer', PACKAGE = 'simer', pBigMat, pBigmat, sirIdx, damIdx, nBlock, op, threads))
}

hasNA <- function(pBigMat, threads = 0L) {
    .Call('_simer_hasNA', PACKAGE = 'simer', pBigMat, threads)
}

hasNABed <- function(bed_file, ind, maxLine, threads = 0L, verbose = TRUE) {
    .Call('_simer_hasNABed', PACKAGE = 'simer', bed_file, ind, maxLine, threads, verbose)
}

PedigreeCorrector <- function(pBigMat, rawGenoID, rawPed, candSirID = NULL, candDamID = NULL, exclThres = 0.005, assignThres = 0.02, birthDate = NULL, threads = 0L, verbose = TRUE) {
    .Call('_simer_PedigreeCorrector', PACKAGE = 'simer', pBigMat, rawGenoID, rawPed, candSirID, candDamID, exclThres, assignThres, birthDate, threads, verbose)
}

