# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SNPHWE2 <- function(obs_hets, obs_hom1, obs_hom2, midp) {
    .Call('_simer_SNPHWE2', PACKAGE = 'simer', obs_hets, obs_hom1, obs_hom2, midp)
}

GenoFilter <- function(pBigMat, keepInds = NULL, filterGeno = NULL, filterHWE = NULL, filterMind = NULL, filterMAF = NULL, threads = 0L, verbose = TRUE) {
    .Call('_simer_GenoFilter', PACKAGE = 'simer', pBigMat, keepInds, filterGeno, filterHWE, filterMind, filterMAF, threads, verbose)
}

hasNA <- function(pBigMat, threads = 0L) {
    .Call('_simer_hasNA', PACKAGE = 'simer', pBigMat, threads)
}

hasNABed <- function(bed_file, ind, maxLine, threads = 0L, verbose = TRUE) {
    .Call('_simer_hasNABed', PACKAGE = 'simer', bed_file, ind, maxLine, threads, verbose)
}

PedigreeCorrector <- function(pBigMat, rawGenoID, rawPed, candSirID = NULL, candDamID = NULL, exclThres = 0.005, assignThres = 0.02, birthDate = NULL, threads = 0L, verbose = TRUE) {
    .Call('_simer_PedigreeCorrector', PACKAGE = 'simer', pBigMat, rawGenoID, rawPed, candSirID, candDamID, exclThres, assignThres, birthDate, threads, verbose)
}

