# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

write_bfile <- function(pBigMat, bed_file, mrkbycol = TRUE, threads = 0L, verbose = TRUE) {
    invisible(.Call('_simer_write_bfile', PACKAGE = 'simer', pBigMat, bed_file, mrkbycol, threads, verbose))
}

read_bfile <- function(bed_file, pBigMat, maxLine, threads = 0L, verbose = TRUE) {
    invisible(.Call('_simer_read_bfile', PACKAGE = 'simer', bed_file, pBigMat, maxLine, threads, verbose))
}

GenoFilter <- function(pBigMat, NA_C, keepIndsNull = NULL, filterGeno = NULL, filterHWE = NULL, filterMind = NULL, filterMAF = NULL, threads = 0L, verbose = TRUE) {
    .Call('_simer_GenoFilter', PACKAGE = 'simer', pBigMat, NA_C, keepIndsNull, filterGeno, filterHWE, filterMind, filterMAF, threads, verbose)
}

Mat2BigMat <- function(pBigMat, mat, indIdxNull = NULL, op = 1L, threads = 0L) {
    invisible(.Call('_simer_Mat2BigMat', PACKAGE = 'simer', pBigMat, mat, indIdxNull, op, threads))
}

BigMat2BigMat <- function(pBigMat, pBigmat, indIdxNull = NULL, op = 1L, threads = 0L) {
    invisible(.Call('_simer_BigMat2BigMat', PACKAGE = 'simer', pBigMat, pBigmat, indIdxNull, op, threads))
}

geno_cvt1_mat <- function(pBigMat, mat, threads = 0L) {
    invisible(.Call('_simer_geno_cvt1_mat', PACKAGE = 'simer', pBigMat, mat, threads))
}

geno_cvt1_bigmat <- function(pBigMat, pBigmat, threads = 0L) {
    invisible(.Call('_simer_geno_cvt1_bigmat', PACKAGE = 'simer', pBigMat, pBigmat, threads))
}

geno_cvt2_mat <- function(pBigMat, mat, threads = 0L) {
    invisible(.Call('_simer_geno_cvt2_mat', PACKAGE = 'simer', pBigMat, mat, threads))
}

geno_cvt2_bigmat <- function(pBigMat, pBigmat, threads = 0L) {
    invisible(.Call('_simer_geno_cvt2_bigmat', PACKAGE = 'simer', pBigMat, pBigmat, threads))
}

bigt_mat <- function(pBigMat, mat, threads = 0L) {
    invisible(.Call('_simer_bigt_mat', PACKAGE = 'simer', pBigMat, mat, threads))
}

bigt_bigmat <- function(pBigMat, pBigmat, threads = 0L) {
    invisible(.Call('_simer_bigt_bigmat', PACKAGE = 'simer', pBigMat, pBigmat, threads))
}

impute_marker <- function(pBigMat, mrkbycol = TRUE, threads = 0L, verbose = TRUE) {
    invisible(.Call('_simer_impute_marker', PACKAGE = 'simer', pBigMat, mrkbycol, threads, verbose))
}

hasNA <- function(pBigMat, mrkbycol = TRUE, geno_ind = NULL, marker_ind = NULL, threads = 1L) {
    .Call('_simer_hasNA', PACKAGE = 'simer', pBigMat, mrkbycol, geno_ind, marker_ind, threads)
}

hasNABed <- function(bed_file, ind, maxLine, threads = 0L, verbose = TRUE) {
    .Call('_simer_hasNABed', PACKAGE = 'simer', bed_file, ind, maxLine, threads, verbose)
}

PedigreeCorrector <- function(pBigMat, rawGenoID, rawPed, candSirID = NULL, candDamID = NULL, exclThres = 0.005, assignThres = 0.02, birthDate = NULL, threads = 0L, verbose = TRUE) {
    .Call('_simer_PedigreeCorrector', PACKAGE = 'simer', pBigMat, rawGenoID, rawPed, candSirID, candDamID, exclThres, assignThres, birthDate, threads, verbose)
}

